### ISSUE TITLE
Some clusters fall outside the administrative boundaries of Somalia - displayed as in Ethiopia

### ISSUE THREAD

**Issue by AndreasSahlberg** [kartoza/least-cost-electrification-somalia#12]
![image](https://user-images.githubusercontent.com/35484968/97288581-50f5de80-1846-11eb-8d7c-72af5e1bcc7b.png)

**Comment by AndreasSahlberg** [comment]
I have asked Abdisalam for updated boundaries. Will see if there is another dataset we could use. In any case, I believe the admin boundaries layer are hard-coded somewhere for the whole globe and would need to be replaced if possible

**Comment by AndreasSahlberg** [comment]
@meomancer please add the following layer from the SDI to the "toggle layers" list: http://somalia.gep.kartoza.com/layers/geonode:country_boundaries
Layer name should be: **Country boundaries**
If possible, the  default option for this layer should be to be displayed (as opposed to the other layers that are not visualized by default).

**Comment by meomancer** [comment]
it is done
