### ISSUE TITLE
Add the following layers to the toggle layers on the visualization platform:

### ISSUE THREAD

**Issue by AndreasSahlberg** [kartoza/least-cost-electrification-somalia#15]
http://somalia.gep.kartoza.com/layers/geonode_data:geonode:Integrated_transmission_backbone
Name: National transmission backbone

http://somalia.gep.kartoza.com/layers/geonode_data:geonode:Split_transmission_backbone
Name: Split transmission backbone

**Comment by meomancer** [comment]
this is done
