### ISSUE TITLE
Update logos on start page

### ISSUE THREAD

**Issue by AndreasSahlberg** [kartoza/least-cost-electrification-somalia#21]
Please replace the World Bank/ESMAP logos on http://somalia.gep.kartoza.com/gep with the Ministry of Energy and Water Resources logo 
![image](https://user-images.githubusercontent.com/35484968/104121419-5e4b4100-533e-11eb-9198-2535e3316ca1.png)

**Comment by AndreasSahlberg** [comment]
Logo available here (moewr_main_logo.jpg): 
https://drive.google.com/drive/u/0/folders/1_wD98l3W6aem6C0SPR5YjlZ5VZfKTojN

**Comment by meomancer** [comment]
This is done
