### ISSUE TITLE
Update text on info page: http://somalia.gep.kartoza.com/gep/about

### ISSUE THREAD

**Issue by AndreasSahlberg** [kartoza/least-cost-electrification-somalia#22]

**Comment by AndreasSahlberg** [comment]
Text available here: https://docs.google.com/document/d/1QGtqrqP-yDYqFjO0JvVjJirBTaJDsXZ0MWQHGV1viNU/edit
Also, add the MoEWR logo on this page: https://drive.google.com/drive/u/0/folders/1_wD98l3W6aem6C0SPR5YjlZ5VZfKTojN

**Comment by AndreasSahlberg** [comment]
@meomancer please update Nicolinas email to nlindblad@worldbank.org. 
We can leave the WB/ESMAP logos on there for now.

**Comment by meomancer** [comment]
this is done
