### ISSUE TITLE
Update toggle layers for intermediate workshop

### ISSUE THREAD

**Issue by AndreasSahlberg** [kartoza/least-cost-electrification-somalia#24]
Could you make the following layers available to be visualized on the platform ("toggle layers") by Monday?
Existing mini-grids: http://somalia.gep.kartoza.com/layers/geonode_data:geonode:Existing_mini_grids
Existing MV lines: http://somalia.gep.kartoza.com/layers/geonode_data:geonode:Existing_MV_line_locations
Schools (should replace the one that is currently there): http://somalia.gep.kartoza.com/layers/geonode_data:geonode:Primary_and_secondary_schools
Potential hydro mini-grid sites:
http://somalia.gep.kartoza.com/layers/geonode_data:geonode:Potential_MG_hydro_sites
Country boundaries: http://somalia.gep.kartoza.com/layers/geonode_data:geonode:country_boundaries1 (should replace/update the one that is currently there)

**Comment by meomancer** [comment]
this is done
