### ISSUE TITLE
Update toggle layers for intermediate workshop#2

### ISSUE THREAD

**Issue by babakkhavari** [kartoza/least-cost-electrification-somalia#28]
Could you make the following layer available to be visualized on the platform ("toggle layers") by Tuesday?
Sesame harvested area: http://somalia.gep.kartoza.com/layers/geonode_data:geonode:harvested_area_for_platform

**Comment by meomancer** [comment]
Done @babakkhavari

**Comment by babakkhavari** [comment]
Great, thanks!
