### ISSUE TITLE
Clusters to SDI

### ISSUE THREAD

**Issue by babakkhavari** [kartoza/least-cost-electrification-somalia#29]
@meomancer I have uploaded a set of clusters here: https://drive.google.com/drive/u/1/folders/1f7jHn76LhuPhaxUrQaNC9koW97i-2k-I

Can these clusters be uploaded on the SDI? No need to visualize, we just want to enable people to find them on the SDI. I can not do it without the SDI getting a server error

![image](https://user-images.githubusercontent.com/35455877/104919211-2b382b80-5996-11eb-8a2d-14a9159c3c50.png)

**Comment by meomancer** [comment]
hi @babakkhavari 
it seems it's from our architecture
i need time to analyze and fix it, but i can't do it for today workshop
it will make website down
could we do after workshop?

**Comment by babakkhavari** [comment]
Hi @meomancer
Yes, it does not have to be done before the workshop today, we can save it for later.

**Comment by meomancer** [comment]
hi @babakkhavari 
is that cluster same with the cluster on the GEP that we use now?

**Comment by babakkhavari** [comment]
Hi @meomancer, yes but with some additional attributes

**Comment by babakkhavari** [comment]
Hello @meomancer, where there every any solution to this? I am still facing the same error when trying now. Is it perhaps because of the size of the file?

**Comment by meomancer** [comment]
hi @babakkhavari 
i'm really sorry to make this ticket wait too long
i will look into it on monday
make sure the cluster on the ticket is in SDI

**Comment by meomancer** [comment]
hi @babakkhavari 
i pulled the cluster to SDI in here:
https://somalia.gep.kartoza.com/layers/somalia-cluster-sdi:geonode:somalia-cluster-sdi

could you check it?

**Comment by babakkhavari** [comment]
Looks good @meomancer, thank you!
