### ISSUE TITLE
Update rise score

### ISSUE THREAD

**Issue by babakkhavari** [kartoza/least-cost-electrification-somalia#32]
I am not sure about how the platform reads the rise score, but the page that it links to states that the rise score for Somalia is 15, while our platform states 4. Can this be updated?

![image](https://user-images.githubusercontent.com/35455877/105028793-c80bcf00-5a51-11eb-8ceb-0b787a26dd5d.png)

https://rise.worldbank.org/scores

**Comment by meomancer** [comment]
this fixed by : https://github.com/kartoza/global-electrification-platform-data-service/commit/7bb85f8d6dc9687399328d73bf7d81ce922c31ad

![Selection_065](https://user-images.githubusercontent.com/4530905/107454166-1b6bcb80-6b7f-11eb-8b0a-1ac80aa2af08.png)
