### ISSUE TITLE
Pop up menu for intermediate year

### ISSUE THREAD

**Issue by babakkhavari** [kartoza/least-cost-electrification-somalia#33]
The pop-up menu when clicking on clusters seems to show 2030 values even if the year selected for analysis is 2025. Can this be updated?

![image](https://user-images.githubusercontent.com/35455877/105028983-099c7a00-5a52-11eb-957b-3fb699b55e72.png)

**Comment by AndreasSahlberg** [comment]
This seems to be a bug. If I select the different year and click apply. it does not update the value of the cluster. However, if I refresh the page afterwards the values will update.

**Comment by meomancer** [comment]
Hi @AndreasSahlberg @babakkhavari 
PR for this fix:
https://github.com/kartoza/global-electrification-platform-explorer/pull/8

![Peek 2021-02-10 12-53](https://user-images.githubusercontent.com/4530905/107471296-7f05f100-6b9f-11eb-8110-ccce4e64d0dd.gif)

**Comment by meomancer** [comment]
Added Year on title in popup
![Selection_069](https://user-images.githubusercontent.com/4530905/107473848-e756d180-6ba3-11eb-870c-2feeb3f35609.png)
