### ISSUE TITLE
Add feature count on the visualization platform

### ISSUE THREAD

**Issue by AndreasSahlberg** [kartoza/least-cost-electrification-somalia#34]
Is it possible to add a Feature count on the platform, that indicates the number of clusters that are visualized, and adjusts when filtering the results?

**Comment by AndreasSahlberg** [comment]
If possible, the platform should show how many clusters are displayed on the platform after applying filters (i.e. ~48 if the above were the only clusters displayed after applying the filters, don't mind the zoom).

![image](https://user-images.githubusercontent.com/35484968/107410979-466a0700-6b0e-11eb-93d5-3a57dda6747a.png)

**Comment by meomancer** [comment]
hi @AndreasSahlberg 
something like this?
PR : https://github.com/kartoza/global-electrification-platform-explorer/pull/7
![Selection_067](https://user-images.githubusercontent.com/4530905/107462994-e025c880-6b8f-11eb-8d25-d459d4e19178.png)
![Selection_068](https://user-images.githubusercontent.com/4530905/107462999-e1ef8c00-6b8f-11eb-8c9c-c2a2b23fe991.png)
