### ISSUE TITLE
Add connection per household filtering option. 

### ISSUE THREAD

**Issue by AndreasSahlberg** [kartoza/least-cost-electrification-somalia#37]
From the WB team: "Is it possible to include a filtering option indicating the economy of new connections. Eg. USD/kWh or USD/connection. So that one can filter out the most economically viable investments."

@AndreasSahlberg can add this information (USD/kWh) to the result files.
@meomancer is it possible to add this as a filter with a slider, in the same way that the population filter is implemented?
![image](https://user-images.githubusercontent.com/35484968/107344824-311bbb00-6ac3-11eb-9296-a16fffd91f8b.png)

**Comment by meomancer** [comment]
the every data is based on scenario, so we need to update the scenarios for the enonomy @AndreasSahlberg ?
So the scenarios is for every cluster, we need to put USD/kWh.

**Comment by AndreasSahlberg** [comment]
@meomancer, I have uploaded new results called **updated_results.zip** here: https://drive.google.com/drive/folders/15quQoRmSAf46Duo_DUEevRO6KXffChW3 
They have a column called 'CostPerConnection2025' and 'CostPerConnection2030' if we can do them year-specific, otherwise use the column 'CostPerConnection', thanks!

**Comment by AndreasSahlberg** [comment]
When I set the CostPerConnection filter quite low (250 USD in the first scenario) it seems that some of the clusters that meet this requirement are not visualized. According to the feature count there should be about ~1600 settlements, but I only see some in northern parts of Somalia which (I think) don't add up to 1600. 

![image](https://user-images.githubusercontent.com/35484968/108174324-955fff80-70ff-11eb-879d-2e52b3542f6e.png)

**Comment by meomancer** [comment]
hi @AndreasSahlberg 
After i check, it is correct on the cluster @AndreasSahlberg 

Here is the number of the features on that filters (134-250 USD per connection)
![Selection_133](https://user-images.githubusercontent.com/4530905/108177650-1639ee00-7136-11eb-98fc-f8e6fc12fa96.png)

And here is in the qgis and everything is really in northern part (the black dot on the map)
![Selection_136](https://user-images.githubusercontent.com/4530905/108177877-5a2cf300-7136-11eb-8a04-c39c17b00cc2.png)

From the features on the cluster, it is 1638 in total
![Selection_135](https://user-images.githubusercontent.com/4530905/108177811-41bcd880-7136-11eb-85dd-903d2036c371.png)

**Comment by AndreasSahlberg** [comment]
Ah ok, my bad, then everything seems good!
