### ISSUE TITLE
Support Question from SEAP

### ISSUE THREAD

**Issue by lucernae** [kartoza/least-cost-electrification-somalia#47]
Hi, I've been contacted by Ismail (SEAP). He asked the following question which I couldn't respond immediately because I'm not too familiar with the underlying stack (I only knew the deployment method).

I will drop the question now and elaborate as we go further. I'm not sure to whom this should be assigned.

The questions:

- [x] <del>The basemap “seems to be outdated” can we update it (is it default).  @seabilwe </del> Marked as non issue since @meomancer demoed that it works fine. Possibly only browser/connection issues
- [x] The boundary line (black one is not correct) @seabilwe 
- [x] ~~The popup is not showing when you click one of the points~~ Marked as non issue since @meomancer demoed that it works fine. Possibly only browser/connection issues
- [x] We need to make sure it is working so the link can be included in GEP (World Bank) portal

**Comment by lucernae** [comment]
1. The basemap "seems to be outdated"

As I understand, the current basemap in SEP page is based on MapBox + OpenStreetMap.
<img width="885" alt="image" src="https://user-images.githubusercontent.com/831865/140736395-1e620d14-3da7-4885-8505-9db389d65466.png">

Zooming in will reveal several town names:
<img width="942" alt="image" src="https://user-images.githubusercontent.com/831865/140736619-e3072bfe-7c30-41d3-8293-b3617147f46f.png">

Some area in the eastern part looks very empty:
<img width="965" alt="image" src="https://user-images.githubusercontent.com/831865/140736810-4174406f-0912-4425-9a25-b1918daf0fd6.png">


It is not clear to me wether there is actually no data there, or the basemap itself is outdated? If it is, can we update it, or provide several basemap as a comparison (perhaps compare it with OSM).

**Comment by lucernae** [comment]
2. The boundary line (black one is not correct).

This one is pretty self explanatory. We need to make sure the boundary line (black line) matches the basemap.
As an example, this doesn't match (gray line from the basemap vs black line from the boundaries):

<img width="657" alt="image" src="https://user-images.githubusercontent.com/831865/140737133-afb1d605-b9d5-4209-b9cc-f4668108e106.png">

I think we can just fix the spatial data for the boundaries. But I don't know how to deploy that (or if it was hardcoded).
So perhaps this issue is more for GIS specialist?

**Comment by lucernae** [comment]
3. The popup is not showing when you click one of the points

This is an example of the popup

<img width="764" alt="image" src="https://user-images.githubusercontent.com/831865/140737481-c378cb48-7c53-4c10-9dc4-e967765d8991.png">

But sometimes, the popup won't show up.

I have no idea what to test. Perhaps the developer can answer this question:
- What object is clickable?
- Where does the data came from
- What is the possible cause of the popup not responding (no popup show up vs popup show up in loading state)
- Was popup data populated before the rendering?

From the deployment side, we can also benchmark the network request that happens when we click popup (if it is indeed network issue). However, currently I'm not sure what kind of object is clickable and can provide those popup.

**Comment by lucernae** [comment]
4. We need to make sure it is working so the link can be included in GEP (World Bank) portal

Basically when all the issues are resolved, we need to tell World Bank to use the new DNS address: somalielectrification.so . Link mentioned is here: https://electrifynow.energydata.info/countries/SO/models

I don't actually know who can change this? Is it KTH? Should we request it to them later?

**Comment by NyakudyaA** [comment]
>     1. The basemap "seems to be outdated"
> 
> 
> As I understand, the current basemap in SEP page is based on MapBox + OpenStreetMap. <img alt="image" width="885" src="https://user-images.githubusercontent.com/831865/140736395-1e620d14-3da7-4885-8505-9db389d65466.png">
> 
> Zooming in will reveal several town names: <img alt="image" width="942" src="https://user-images.githubusercontent.com/831865/140736619-e3072bfe-7c30-41d3-8293-b3617147f46f.png">
> 
> Some area in the eastern part looks very empty: <img alt="image" width="965" src="https://user-images.githubusercontent.com/831865/140736810-4174406f-0912-4425-9a25-b1918daf0fd6.png">
> 
> It is not clear to me wether there is actually no data there, or the basemap itself is outdated? If it is, can we update it, or provide several basemap as a comparison (perhaps compare it with OSM).

We can alternatively provide a base map made up of layers from OSM or their own boundary layers or simply overlay the boundaries / town names

**Comment by meomancer** [comment]
hi @lucernae 
i tried by my self for popup
but i can't produce it
maybe we can ask client to record how they reproduce?

**Comment by lucernae** [comment]
@meomancer did you try it in https://somalielectrification.so ? I think it's best if you ask the client directly. I can setup the meeting if you want.

I couldn't answer the question myself because I don't know which objects are supposed to be clickable:

> What object is clickable?
    Where does the data came from
    What is the possible cause of the popup not responding (no popup show up vs popup show up in loading state)
    Was popup data populated before the rendering?

But in the previous meeting, I can confirm that the popup doesn't show up in their browser.

**Comment by meomancer** [comment]
@lucernae 
it is just cluster that able to be clicked

yes, i think the best way is talking with client directly

**Comment by lkwalke4** [comment]
@seabilwe I think we need to move forward with the doing the same thing we did for Somaliland - getting a custom basemap together to use, since it appears Somalia's boundaries don't align with the open street map version. Can you please start work on this?

**Comment by lkwalke4** [comment]
@lucernae could you please set up the meeting with Irwan to discuss the pop up issue? Can you please CC me on that meeting?

**Comment by lkwalke4** [comment]
> 
> 
>     1. We need to make sure it is working so the link can be included in GEP (World Bank) portal
> 
> 
> Basically when all the issues are resolved, we need to tell World Bank to use the new DNS address: somalielectrification.so . Link mentioned is here: https://electrifynow.energydata.info/countries/SO/models
> 
> I don't actually know who can change this? Is it KTH? Should we request it to them later?

@lucernae  - I will coordinate with Nicolina on this once we are complete with the fixes.

**Comment by lucernae** [comment]
> @lucernae could you please set up the meeting with Irwan to discuss the pop up issue? Can you please CC me on that meeting?

@lkwalke4 , sorry the client uses their Zoom account, so the invite comes from them, and the time is too early for you so we went along. I will instead CC you in the meeting recap/notes.

As discussed in the meetings, the clients has accepted that the two of the issues previously mentioned are possibly browser/network issues instead of bug. So we mark it as solved. The boundary issue still needs to be solved.

The client also raises several follow up issue. I will wrote it up in separate ticket.

CC @meomancer @lkwalke4

**Comment by lucernae** [comment]
Hi everyone, 

@seabilwe made the new boundaries here:
https://somalielectrification.so/layers/geonode:som_country_boundary


I've changed the new boundaries link in this json config (currently only in the server):

https://github.com/kartoza/global-electrification-platform-explorer/blob/9aaa2093662cf067017ae5dd9bddf258176a3d43/app/assets/scripts/config/externalLayers.json#L19

But as you can see these parts are still not matched: 
<img width="372" alt="image" src="https://user-images.githubusercontent.com/831865/142988430-3c58de34-9a43-495f-bc10-909aa0499944.png">

To confirm that it is indeed using the new boundaries, I check the loaded config json in the browser:
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/831865/142988548-89817223-b202-41ea-8d32-eef9c2d446bf.png">

So, @meomancer @lkwalke4 @seabilwe , how are we going to proceed?
Do we change the mapbox basemap to OSM or attempt to make the boundaries match with the mapbox basemap.
Not sure which one is the correct one, though.

**Comment by lucernae** [comment]
From the email correspondence with the client, I think we can close this ticket as it has been fixed by @seabilwe .
