### ISSUE TITLE
Need more descriptions on popup regarding investments and capacity values.

### ISSUE THREAD

**Issue by lucernae** [kartoza/least-cost-electrification-somalia#48]
From the discussion in 18 Nov with the client, they are a little bit confused about what the values means in the popup and why it seems to be not consistent with the summary sidebar.

Screenshots below for demo:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/831865/142379708-d1467718-2f1f-42be-976b-4b21b4d67ead.png">

Problem is: investments only shows around 54 million, but total in summary shows 376 million.

@meomancer  has indicated that the count itself in the summary panel is correct because it is counting based on the left panel filters. In this particular example, the remaining "missing" investments comes from the time range from 2025 to 2030. However the popup only shows investments data of timeslice between 2025 to 2030, meanwhile the total summary includes data from before 2025 **and** up to 2030. If we change the timeslice to 2025, we can see that the popup shows investments around 300 million.

@meomancer suggests that we can improve the popup clarity by doing these:
- keep the summary as is, because the behaviour is already correct
- popup needs to show "INVESTMENT REQUIRED IN TIMESTEP (the year range)" and something like "TOTAL INVESTMENT UPTO (the year)"
- since the added capacity information is also timestep based, perhaps we also need to add something like "TOTAL ADDED CAPACITY UPTO (the year)" info. Similar logic with total investment.

Since this is development issue, I will let developer handle it and ping me when it needs redeployment.

CC @lkwalke4 @timlinux @meomancer

**Comment by meomancer** [comment]
hi @lucernae 
PR is here:
https://github.com/kartoza/least-cost-electrification-somalia/pull/50

we need to merge and deploy
**frontend** : https://github.com/kartoza/global-electrification-platform-explorer/pull/10
and
**backend** : https://github.com/kartoza/global-electrification-platform-data-service/pull/1https://github.com/kartoza/global-electrification-platform-data-service/pull/1


I found that:
on summary, Investement Cost is total from today to the selected year (2025 + 2030)
but on added capacity, they are not in total

So the PR of backend is change the added capacity to also in total

**Comment by lucernae** [comment]
Hi @meomancer I don't think I have enough knowledge to review. Can you go ahead and merge (both in submodules and this repo), then instruct me how to deploy the changes?
I assume since both are submodules, I have to `git submodule update` and rebuilt the entire containers? CMIIW.

**Comment by meomancer** [comment]
hi @lucernae 
i already deployed that
please check it (and do hard refresh)
![Selection_310](https://user-images.githubusercontent.com/4530905/142634450-37ab89f2-aec8-49a6-91ad-780a14bdd210.png)

**Comment by lucernae** [comment]
Thanks @meomancer ,
Can you just confirm my question here:

> Hi @meomancer I don't think I have enough knowledge to review. Can you go ahead and merge (both in submodules and this repo), then instruct me how to deploy the changes?
I assume since both are submodules, I have to git submodule update and rebuilt the entire containers? CMIIW.

This information is needed for internal deployment procedure document for our DevOps, since this stack does not use k8s.

Please provide any missing steps/procedure so I can document it.

**Comment by meomancer** [comment]
Hi @lucernae 
Yes, just update the submodule
After that restart backend, frontend and ngix container in order

**Comment by lucernae** [comment]
Done, documented in the kartoza/devops as well.
