### ISSUE TITLE
URL in pdf report footer shows localhost:9000

### ISSUE THREAD

**Issue by lucernae** [kartoza/least-cost-electrification-somalia#49]
Probably just a misconfig. See the attached screenshot of pdf report:

[gep-so-1-mini-grids-and-stand-alone-only_no-intensification_low_existing-local-technologies_low_low-0-68-usd-litre.pdf](https://github.com/kartoza/least-cost-electrification-somalia/files/7561346/gep-so-1-mini-grids-and-stand-alone-only_no-intensification_low_existing-local-technologies_low_low-0-68-usd-litre.pdf)

The footer shows:

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/831865/142381461-260b6d5e-4653-41f4-bb9c-dc44f7eef332.png">

It should show the real DNS name. It can be just a configuration issue. Perhaps @meomancer can just show me if there are config to change the URL in the JS build.

**Comment by meomancer** [comment]
The settings that need to be changed should be here
https://github.com/kartoza/global-electrification-platform-explorer/blob/3c2c70ebe5cb27d1a77c5d4a7afc2e0d4464339b/app/assets/scripts/config/production.js#L5

**Comment by meomancer** [comment]
hi @lucernae 
i already fixed it
[gep-so-1-mini-grids-and-stand-alone-only_no-intensification_low_existing-local-technologies_low_low-0-68-usd-litre (1).pdf](https://github.com/kartoza/least-cost-electrification-somalia/files/7570672/gep-so-1-mini-grids-and-stand-alone-only_no-intensification_low_existing-local-technologies_low_low-0-68-usd-litre.1.pdf)

maybe we can close this ticket

**Comment by lucernae** [comment]
Hi @meomancer , thanks I just noticed it when I want to do the deployment today. I also download the pdf and it was working.

**Comment by lucernae** [comment]
Let's close this as it has been fixed.
