### ISSUE TITLE
MapBox BaseMap Does Not Match The Country Boundary Layer Uploaded 

### ISSUE THREAD

**Issue by seabilwe** [kartoza/least-cost-electrification-somalia#51]
Hi @lkwalke4 @timlinux cc @lucernae @meomancer 

I have been correcting the country boundary that was said it did not match the base map in the SEP and the Geonode basemaps in this ticket #47. 
I managed to get it to match the boundaries of the OSM basemaps
![image](https://user-images.githubusercontent.com/56301949/142991281-8403f45e-cba8-499d-ad92-49c25a750e5e.png)
![image](https://user-images.githubusercontent.com/56301949/142991346-5cc0d018-e1f9-4585-a498-6e56448404fd.png)

Now the issue is the mapbox basemap, when placing the country boundary layer on the SEP, the outlines do not match.
For example: 
![image](https://user-images.githubusercontent.com/56301949/142992386-5680fbd3-dd05-4aef-a2b8-6a019ad8dd2e.png)

But also the mapbox's boundaries alone are not aligned properly: 
![image](https://user-images.githubusercontent.com/56301949/142993212-5723d888-dd96-4e47-bfdb-7f5dc5632386.png)

Please note that @lucernae has mentioned this on the #47 
![image](https://user-images.githubusercontent.com/56301949/142993522-0c9d472f-1dfb-42d0-a2bf-48329cb17fd7.png)
![image](https://user-images.githubusercontent.com/56301949/142993574-36d04d91-de6a-48a1-9269-4bbec159f1c1.png)

**Comment by meomancer** [comment]
i think we can change basemap from mapbox to osm?

**Comment by lucernae** [comment]
@meomancer how do we add this basemap just like in somaliland https://somalielectrification.so/geoserver/web/wicket/bookmarkable/org.geoserver.web.data.layergroup.LayerGroupPage?21

I see that in somaliland it was added not as a basemap but a default-active layer. You can just point me to the relevant files and I can try to deploy it on SEAP before we make a commit.

**Comment by lucernae** [comment]
Wait a minute, I think I can just change it in externalLayers.json if it is indeed considered as one, CMIIW @meomancer

**Comment by lucernae** [comment]
I was able to do a quick patch and see the result here:

<img width="839" alt="image" src="https://user-images.githubusercontent.com/831865/143016948-88ea3399-1779-48f7-a8ff-b8e3b30653f8.png">

The mapbox boundaries are still slightly visible.
To see the basemap, enable "Somalia Basemap" from the layer selection.

Perhaps we have to make the basemap more opaque-white or less-transparent to override that wrong boundaries from mapbox? How about it @seabilwe ?

**Comment by seabilwe** [comment]
Okay, I'll remove the transparency that I added to the 'Somalia Basemap' @lucernae

**Comment by seabilwe** [comment]
ive removed the opacity @lucernae

**Comment by lucernae** [comment]
I think this is nice. I will set it as the default basemap for now and ask the client for confirmation. If they are okay with it, we can proceed with the PR.


<img width="863" alt="image" src="https://user-images.githubusercontent.com/831865/143018361-b55d3865-e759-4fe4-91c0-ddd16c187fc6.png">

**Comment by lucernae** [comment]
Done and deployed as the default basemap.
