### ISSUE TITLE
Primary school and secondary schools layer won't render due to missing SLDs.

### ISSUE THREAD

**Issue by lucernae** [kartoza/least-cost-electrification-somalia#52]
From the email attachment from SEAP client:
[gep.pdf](https://github.com/kartoza/least-cost-electrification-somalia/files/7632656/gep.pdf)

<img width="1628" alt="Screen Shot 2021-12-01 at 16 38 53" src="https://user-images.githubusercontent.com/831865/144210053-4d861d41-07ae-4f74-ae2c-0eb674c73c36.png">

It seems that the primary and secondary schools layers won't render. The layer itself is in SEAP geoserver instance.
Do we have any specific SLDs that should be used for this layer?

CC @meomancer @seabilwe ?

**Comment by seabilwe** [comment]
Hi @lucernae, the SLD for the schools is empty, not sure the reason why (someone could have been updating the style, and it got lost), but I will restyle it again. Will be available by the end of the day (SA Time)
![image](https://user-images.githubusercontent.com/56301949/144211229-3c67024b-e879-4507-8bb2-849147f5ea32.png)

**Comment by seabilwe** [comment]
@lucernae Restored the style. I am not sure how it looked previously though, but I hope this suffice 
![image](https://user-images.githubusercontent.com/56301949/144214238-370a7344-b38c-441a-bf56-12a24865aebe.png)

**Comment by lucernae** [comment]
We can close this ticket.
