### ISSUE TITLE
Do not append extra parameters to the URL

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/least-cost-electrification-somalia#8]
# Problem

* Upload a layer to the site.
* navigate to the map layer list and it only shows three layers.
Checking on the URL it shows the following http://somalia.gep.kartoza.com/layers/?limit=5&group__group_profile__slug__in=registered-members&offset=0

Instead of http://somalia.gep.kartoza.com/layers/?limit=5
This applied to the map page view, search page by all options ie keywords etc

**Comment by meomancer** [comment]
Fixed
